#
# Configuration for ACI Fabric
#
aci_config:
  system_id: kubesbx07             # Every opflex cluster must have a distict ID
  apic_hosts:                   # List of APIC hosts to connect for APIC API
  - 10.10.20.12
  vmm_domain:                   # Kubernetes container domain configuration
    encap_type: vxlan           # Encap mode: vxlan or vlan
    mcast_range:                # Every opflex VMM must use a distinct range
      start: 225.207.1.1
      end: 225.207.255.255
    nested_inside:              # Include if nested inside a VMM; required for CloudFoundry
      type: vmware              # Specify the VMM vendor (supported: vmware)
      name: k8s-apic            # Specify the name of the VMM domain

  # The following resources must already exist on the APIC,
  # they are used, but not created by the provisioning tool.
  aep: K8s:AllVLANs-AEP             # The AEP for ports/VPCs used by this cluster
  vrf:                          # This VRF used to create all kubernetes EPs
    name: sbx_shared
    tenant: common              # This can be system-id or common
  l3out:
    name: sbx_shared_L3Out          # Used to provision external IPs
    external_networks:
    - any_ip             # Used for external contracts

#
# Networks used by Kubernetes
# sbx00 172.20.4.0/22  (node, extern)
# sbx00
net_config:
  node_subnet: 172.20.7.1/26      # Subnet to use for nodes
  pod_subnet: 10.207.0.1/16      # Subnet to use for Kubernetes Pods/CloudFoundry containers
    # If deployed containers need to access internet, need to have SNAT on this Subnet
# vip_subnet: 10.3.0.1/16       # Subnet to use for virtual IPs (CloudFoundry only)
  extern_dynamic: 172.20.7.193/27   # Subnet to use for dynamic external IPs  ROUTABLE
  extern_static: 172.20.7.225/27    # Subnet to use for static external IPs   ROUTABLE
  node_svc_subnet: 192.168.107.1/24  # Subnet to use for service graph         NOT ROUTABLE
  kubeapi_vlan: 916            # The VLAN used by the physdom for nodes (Kubernetes only)
  service_vlan: 917            # The VLAN used by LoadBalancer services
  infra_vlan: 4093              # The VLAN used by ACI infra

#
# Configuration for container registry
# Update if a custom container registry has been setup
#
registry:
  image_prefix: noiro                   # e.g: registry.example.com/noiro
  # image_pull_secret: secret_name      # (if needed)